insert into Line_Translations
    (line_translation_lyrics, line_translation_explanation, line_id, language_id, song_instance_id)
values
    ('Quick Stop duplo largo, T-top à meia-noite', 'Quick Stop é um tipo de posto de gasolina; T-top é um tipo de telhado prum carro', 1, 19, 8),
    ('Jack em sua Coca-Cola tipo de cidade', 'Jack Daniels é um tipo de uísque', 2, 19, 8),
    ('Mamãe e papai colocaram suas raízes aqui', 'Eles pararam pra construir uma vida', 3, 19, 8),
    ('Porque aqui é onde o carro quebrou', '', 4, 19, 8),
    ('Ônibus escolar cachorro-amarelo levantando poeira vermelha', 'Cachorro-amarela é uma gíria adjetivo para se referir a o ônibus amarelo clássico dos EUA', 5, 19, 8),
    ('Nos pegando ao lado da cerca de arame farpado', '', 6, 19, 8),
    ('MTV na RCA, sem A/C nos ventiladores', 'MTV é um canal de televisão clássico de vídeos de música; RCA é um rádio clássico; A/C se refere ao ar condicionado', 7, 19, 8),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 8, 19, 8),
    ('Nascidos nos EUA', '', 9, 19, 8),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 10, 19, 8),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 11, 19, 8),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 12, 19, 8),
    ('Querido, vem me dar um beijo', '', 13, 19, 8),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 14, 19, 8),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 15, 19, 8),
    ('Crescendo em casinhas rosas', '', 16, 19, 8),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 17, 19, 8),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 18, 19, 8),
    ('Um pouco estragados, mas estamos todos bem', '', 19, 19, 8),

    ('Estacionamento da Igreja Batista, tentando não ser pegos', 'A Igreja Batista é tradicionalmente a maior denominação cristã do sul dos EUA', 20, 19, 8),
    ('Levá-la pra casa e dar sua jaqueta pra ela', '', 21, 19, 8),
    ('Chegando ao segunda base, mas dizendo que você chegou até o fim', 'Os bases (primeiro, segundo, terceiro, e base de casa) se refere ao basebol americano, mas é um eufemismo para os passos crescentes do contato sexual', 22, 19, 8),
    ('Segunda à tarde no treino', 'Treino de basebol, nesse caso', 23, 19, 8),
    ('Irmã tem um namorado que papai não gosta', '', 24, 19, 8),
    ('Agora ele está sentado atrás, 30/30 no colo dele', 'O .30/30 Winchester é uma arma clássica dos EUA', 25, 19, 8),
    ('Na luz eletrocutora de insectos azul', ' ''Bug-zapper'' é um adjetivo composto que se refere às luzes azuis que se usa pra atrair e matar pernilongos', 26, 19, 8),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 27, 19, 8),
    ('Nascidos nos EUA', '', 28, 19, 8),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 29, 19, 8),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 30, 19, 8),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 31, 19, 8),
    ('Querido, vem me dar um beijo', '', 32, 19, 8),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 33, 19, 8),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 34, 19, 8),
    ('Crescendo em casinhas rosas', '', 35, 19, 8),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 36, 19, 8),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 37, 19, 8),
    ('Um pouco estragados, mas estamos todos bem', '', 38, 19, 8),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 39, 19, 8),
    ('Nascidos nos EUA', '', 40, 19, 8),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 41, 19, 8),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 42, 19, 8),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 43, 19, 8),
    ('Querido, vem me dar um beijo', '', 44, 19, 8),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 45, 19, 8),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 46, 19, 8),
    ('Crescendo em casinhas rosas', '', 47, 19, 8),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 48, 19, 8),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 49, 19, 8),
    ('Um pouco estragados, mas estamos todos bem', '', 50, 19, 8);