insert into Lines
    (line_lyrics, song_instance_id, language_id)
values
    ('Doublewide Quick Stop midnight T-top', 8, 19),
    ('Jack in her Cherry Coke town', 8, 19),
    ('Momma and daddy put their roots right here', 8, 19),
    ('''Cause this is where the car broke down', 8, 19),
    ('Yellow dog school bus kickin’ up red dust', 8, 19),
    ('Pickin’ us up by a barbed wire fence', 8, 19),
    ('MTV on the RCA, no A/C in the vents', 8, 19),

    ('We were Jesus save me, blue jean baby', 8, 19),
    ('Born in the USA', 8, 19),
    ('Trailer park truck stop, faded little map dots', 8, 19),
    ('New York to LA', 8, 19),
    ('We were teenage dreamin’, front seat leanin’', 8, 19),
    ('Baby, come give me a kiss', 8, 19),
    ('Put me on the cover of the Rolling Stone', 8, 19),
    ('Uptown down home American kids', 8, 19),
    ('Growin’ up in little pink houses', 8, 19),
    ('Makin’ out on living room couches', 8, 19),
    ('Blowin’ that smoke on Saturday night', 8, 19),
    ('A little messed up, but we’re all alright', 8, 19),

    ('Baptist church parkin’ lot, tryin’ not to get caught', 8, 19),
    ('Take her home and give her your jacket', 8, 19),
    ('Makin’ it to second base, but sayin’ you went all the way', 8, 19),
    ('Monday afternoon at practice', 8, 19),
    ('Sister''s got a boyfriend daddy doesn’t like', 8, 19),
    ('Now he’s sittin’ out back, 30/30 in his lap', 8, 19),
    ('In the blue bug zapper light', 8, 19),

    ('We were Jesus save me, blue jean baby', 8, 19),
    ('Born in the USA', 8, 19),
    ('Trailer park truck stop, faded little map dots', 8, 19),
    ('New York to LA', 8, 19),
    ('We were teenage dreamin’, front seat leanin’', 8, 19),
    ('Baby, come give me a kiss', 8, 19),
    ('Put me on the cover of the Rolling Stone', 8, 19),
    ('Uptown down home American kids', 8, 19),
    ('Growin’ up in little pink houses', 8, 19),
    ('Makin’ out on living room couches', 8, 19),
    ('Blowin’ that smoke on Saturday night', 8, 19),
    ('A little messed up, but we’re all alright', 8, 19),

    ('We were Jesus save me, blue jean baby', 8, 19),
    ('Born in the USA', 8, 19),
    ('Trailer park truck stop, faded little map dots', 8, 19),
    ('New York to LA', 8, 19),
    ('We were teenage dreamin’, front seat leanin’', 8, 19),
    ('Baby, come give me a kiss', 8, 19),
    ('Put me on the cover of the Rolling Stone', 8, 19),
    ('Uptown down home American kids', 8, 19),
    ('Growin’ up in little pink houses', 8, 19),
    ('Makin’ out on living room couches', 8, 19),
    ('Blowin’ that smoke on Saturday night', 8, 19),
    ('A little messed up, but we’re all alright', 8, 19);