insert into Lines(line_lyrics, line_explanation, line_index, song_instance_id, language_id)
values
('Nacimos para aguantar lo que el cuerpo sostiene', 'una buena explicación aqui xd', 1, 2, 2),
('Aguantamos lo que vino y aguantamos lo que viene', 'una buena explicación aqui xd', 2, 2, 2),
('Aguantamos aunque tengamos los segundos contados', 'una buena explicación aqui xd', 3, 2, 2),
('Nuestro cuerpo aguanta hasta quince minutos ahorcado', 'una buena explicación aqui xd', 4, 2, 2),
('Aguantamos latigazos, que nos corten los dos brazos', 'una buena explicación aqui xd', 5, 2, 2),
('Fractura en cualquier hueso, tres semanas con un yeso', 'una buena explicación aqui xd', 6, 2, 2),

('Aguantamos todo el tiempo las ganas de ir al baño', 'una buena explicación aqui xd', 7, 2, 2),
('Pa ver el cometa Halley, hay que aguantar setenta años', 'una buena explicación aqui xd', 8, 2, 2),
('Aguantamos la escuela, la facultad, el instituto', 'una buena explicación aqui xd', 9, 2, 2),
('A la hora de cenar nos aguantamos los eruptos', 'una buena explicación aqui xd', 10, 2, 2),
('El pueblo de Burundi sigue aguantando la hambruna', 'una buena explicación aqui xd', 11, 2, 2),
('Aguantamos tres días para llegar a la luna', 'una buena explicación aqui xd', 12, 2, 2),

('Aguantamos el frío del Ártico, el calor del trópico', 'una buena explicación aqui xd', 13, 2, 2),
('Aguantamos con anticuerpos los virus microscópicos', 'una buena explicación aqui xd', 14, 2, 2),
('Aguantamos las tormentas, huracanes, el mal clima', 'una buena explicación aqui xd', 15, 2, 2),
('Aguantamos Nagasaki, aguantamos Hiroshima', 'una buena explicación aqui xd', 16, 2, 2),
('Aunque no queramos, aguantamos nuevas leyes', 'una buena explicación aqui xd', 17, 2, 2),
('Aguantamos hoy por hoy que todavía existan reyes', 'una buena explicación aqui xd', 18, 2, 2),
('Castigamos al humilde y aguantamos al cruel', 'una buena explicación aqui xd', 19, 2, 2),
('Aguantamos ser esclavos por nuestro color de piel', 'una buena explicación aqui xd', 20, 2, 2),
('Aguantamos el capitalismo, el comunismo, el socialismo, el feudalismo', 'una buena explicación aqui xd', 21, 2, 2),
('Aguantamos hasta el pendejismo', 'una buena explicación aqui xd', 22, 2, 2),
('Aguantamos al culpable cuando se hace el inocente', 'una buena explicación aqui xd', 23, 2, 2),
('Aguantamos cada año a nuestro p*** presidente', 'una buena explicación aqui xd', 24, 2, 2),

('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 25, 2, 2),
('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 26, 2, 2),
('Por lo que venga y por este instante', 'una buena explicación aqui xd', 27, 2, 2),
('A brindar por el aguante', 'una buena explicación aqui xd', 28, 2, 2),
('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 29, 2, 2),
('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 30, 2, 2),
('Por lo que venga y por este instante', 'una buena explicación aqui xd', 31, 2, 2),
('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 32, 2, 2),
('A brindar por el aguante', 'una buena explicación aqui xd', 33, 2, 2),

('Aguantamos que Monsanto infecte nuestra comida', 'una buena explicación aqui xd', 34, 2, 2),
('Aguantamos el agente naranja y los pesticidas', 'una buena explicación aqui xd', 35, 2, 2),
('Cuando navegamos, aguantamos el mareo', 'una buena explicación aqui xd', 36, 2, 2),
('Aguantamos el salario mínimo y el desempleo', 'una buena explicación aqui xd', 37, 2, 2),
('Aguantamos las Malvinas y la invasion británica', 'una buena explicación aqui xd', 38, 2, 2),
('En la ciudad de Pompeya aguantamos lava volcánica', 'una buena explicación aqui xd', 39, 2, 2),

('Y dentro de la lógica de nuestra humanidad', 'una buena explicación aqui xd', 40, 2, 2),
('Nos creemos la mentira y nadie aguanta la verdad', 'una buena explicación aqui xd', 41, 2, 2),

('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 42, 2, 2),
('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 43, 2, 2),
('Por lo que venga y por este instante', 'una buena explicación aqui xd', 44, 2, 2),
('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 45, 2, 2),
('A brindar por el aguante', 'una buena explicación aqui xd', 46, 2, 2),

('Aguantamos al ateo, al mormón, al cristiano', 'una buena explicación aqui xd', 47, 2, 2),
('Al budista, al judío, aguantamos al pagano', 'una buena explicación aqui xd', 48, 2, 2),
('Aguantamos el que vende balas y el que las dispara', 'una buena explicación aqui xd', 49, 2, 2),
('Aguantamos la muerte de Lenon, la de Víctor Jara', 'una buena explicación aqui xd', 50, 2, 2),
('Aguantamos muchas guerras: Vietnam, la Guerra Fría', 'una buena explicación aqui xd', 51, 2, 2),
('La Guerra de los Cien Años, la Guerra de los Seis días', 'una buena explicación aqui xd', 52, 2, 2),
('Que aguanten la revancha venimos al desquite', 'una buena explicación aqui xd', 53, 2, 2),
('Hoy nuestro hígado aguanta lo que la barra invite', 'una buena explicación aqui xd', 54, 2, 2),

('Aguantamos ser esclavos por nuestro color de piel', 'una buena explicación aqui xd', 55, 2, 2),

('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 56, 2, 2),
('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 57, 2, 2),
('Por lo que venga y por este instante', 'una buena explicación aqui xd', 58, 2, 2),
('A brindar por el aguante', 'una buena explicación aqui xd', 59, 2, 2),

('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 60, 2, 2),
('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 61, 2, 2),
('Por lo que venga y por este instante', 'una buena explicación aqui xd', 62, 2, 2),
('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 63, 2, 2),
('A brindar por el aguante', 'una buena explicación aqui xd', 64, 2, 2);