insert into Lines
    (line_lyrics, line_index, song_instance_id, language_id)
values
    ('Doublewide Quick Stop midnight T-top', 1, 5, 1),
    ('Jack in her Cherry Coke town', 2, 5, 1),
    ('Momma and daddy put their roots right here', 3, 5, 1),
    ('''Cause this is where the car broke down', 4, 5, 1),
    ('Yellow dog school bus kickin’ up red dust', 5, 5, 1),
    ('Pickin’ us up by a barbed wire fence', 6, 5, 1),
    ('MTV on the RCA, no A/C in the vents', 7, 5, 1),

    ('We were Jesus save me, blue jean baby', 8, 5, 1),
    ('Born in the USA', 9, 5, 1),
    ('Trailer park truck stop, faded little map dots', 10, 5, 1),
    ('New York to LA', 11, 5, 1),
    ('We were teenage dreamin’, front seat leanin’', 12, 5, 1),
    ('Baby, come give me a kiss', 13, 5, 1),
    ('Put me on the cover of the Rolling Stone', 14, 5, 1),
    ('Uptown down home American kids', 15, 5, 1),
    ('Growin’ up in little pink houses', 16, 5, 1),
    ('Makin’ out on living room couches', 17, 5, 1),
    ('Blowin’ that smoke on Saturday night', 18, 5, 1),
    ('A little messed up, but we’re all alright', 19, 5, 1),

    ('Baptist church parkin’ lot, tryin’ not to get caught', 20, 5, 1),
    ('Take her home and give her your jacket', 21, 5, 1),
    ('Makin’ it to second base, but sayin’ you went all the way', 22, 5, 1),
    ('Monday afternoon at practice', 23, 5, 1),
    ('Sister''s got a boyfriend daddy doesn’t like', 24, 5, 1),
    ('Now he’s sittin’ out back, 30/30 in his lap', 25, 5, 1),
    ('In the blue bug zapper light', 26, 5, 1),

    ('We were Jesus save me, blue jean baby', 27, 5, 1),
    ('Born in the USA', 28, 5, 1),
    ('Trailer park truck stop, faded little map dots', 29, 5, 1),
    ('New York to LA', 30, 5, 1),
    ('We were teenage dreamin’, front seat leanin’', 31, 5, 1),
    ('Baby, come give me a kiss', 32, 5, 1),
    ('Put me on the cover of the Rolling Stone', 33, 5, 1),
    ('Uptown down home American kids', 34, 5, 1),
    ('Growin’ up in little pink houses', 35, 5, 1),
    ('Makin’ out on living room couches', 36, 5, 1),
    ('Blowin’ that smoke on Saturday night', 37, 5, 1),
    ('A little messed up, but we’re all alright', 38, 5, 1),

    ('We were Jesus save me, blue jean baby', 39, 5, 1),
    ('Born in the USA', 40, 5, 1),
    ('Trailer park truck stop, faded little map dots', 41, 5, 1),
    ('New York to LA', 42, 5, 1),
    ('We were teenage dreamin’, front seat leanin’', 43, 5, 1),
    ('Baby, come give me a kiss', 44, 5, 1),
    ('Put me on the cover of the Rolling Stone', 45, 5, 1),
    ('Uptown down home American kids', 46, 5, 1),
    ('Growin’ up in little pink houses', 47, 5, 1),
    ('Makin’ out on living room couches', 48, 5, 1),
    ('Blowin’ that smoke on Saturday night', 49, 5, 1),
    ('A little messed up, but we’re all alright', 50, 5, 1);

insert into Line_Translations
    (line_translation_lyrics, line_translation_explanation, line_id, language_id, song_instance_id, line_index)
values
    ('Quick Stop duplo largo, T-top à meia-noite', 'Quick Stop é um tipo de posto de gasolina; T-top é um tipo de telhado prum carro', 1, 3, 5, 1),
    ('Jack em sua Coca-Cola tipo de cidade', 'Jack Daniels é um tipo de uísque', 2, 3, 5, 2),
    ('Mamãe e papai colocaram suas raízes aqui', 'Eles pararam pra construir uma vida', 3, 3, 5, 3),
    ('Porque aqui é onde o carro quebrou', '', 4, 3, 5, 4),
    ('Ônibus escolar cachorro-amarelo levantando poeira vermelha', 'Cachorro-amarela é uma gíria adjetivo para se referir a o ônibus amarelo clássico dos EUA', 5, 3, 5, 5),
    ('Nos pegando ao lado da cerca de arame farpado', '', 6, 3, 5, 6),
    ('MTV na RCA, sem A/C nos ventiladores', 'MTV é um canal de televisão clássico de vídeos de música; RCA é um rádio clássico; A/C se refere ao ar condicionado', 7, 3, 5, 7),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 8, 3, 5, 8),
    ('Nascidos nos EUA', '', 9, 3, 5, 9),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 10, 3, 5, 10),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 11, 3, 5, 11),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 12, 3, 5, 12),
    ('Querido, vem me dar um beijo', '', 13, 3, 5, 13),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 14, 3, 5, 14),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 15, 3, 5, 15),
    ('Crescendo em casinhas rosas', '', 16, 3, 5, 16),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 17, 3, 5, 17),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 18, 3, 5, 18),
    ('Um pouco estragados, mas estamos todos bem', '', 19, 3, 5, 19),

    ('Estacionamento da Igreja Batista, tentando não ser pegos', 'A Igreja Batista é tradicionalmente a maior denominação cristã do sul dos EUA', 20, 3, 5, 20),
    ('Levá-la pra casa e dar sua jaqueta pra ela', '', 21, 3, 5, 21),
    ('Chegando ao segunda base, mas dizendo que você chegou até o fim', 'Os bases (primeiro, segundo, terceiro, e base de casa) se refere ao basebol americano, mas é um eufemismo para os passos crescentes do contato sexual', 22, 3, 5, 22),
    ('Segunda à tarde no treino', 'Treino de basebol, nesse caso', 23, 3, 5, 23),
    ('Irmã tem um namorado que papai não gosta', '', 24, 3, 5, 24),
    ('Agora ele está sentado atrás, 30/30 no colo dele', 'O .30/30 Winchester é uma arma clássica dos EUA', 25, 3, 5, 25),
    ('Na luz eletrocutora de insectos azul', ' ''Bug-zapper'' é um adjetivo composto que se refere às luzes azuis que se usa pra atrair e matar pernilongos', 26, 3, 5, 26),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 27, 3, 5, 27),
    ('Nascidos nos EUA', '', 28, 3, 5, 28),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 29, 3, 5, 29),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 30, 3, 5, 30),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 31, 3, 5, 31),
    ('Querido, vem me dar um beijo', '', 32, 3, 5, 32),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 33, 3, 5, 33),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 34, 3, 5, 34),
    ('Crescendo em casinhas rosas', '', 35, 3, 5, 35),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 36, 3, 5, 36),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 37, 3, 5, 37),
    ('Um pouco estragados, mas estamos todos bem', '', 38, 3, 5, 38),

    ('Nós éramos Jesus-salve-me, jeans-azul-bebê', 'Gírias adjetivos para se referir às pessoas rurais que amam Jesus e usam jeans azul', 39, 3, 5, 39),
    ('Nascidos nos EUA', '', 40, 3, 5, 40),
    ('Paradas de caminhões, parque de trailers, pontos pequenos desvanecidos no mapa', 'Explicam que pros outros, eles eram só um pontinho no mapa pra estacionar o camião ou um trailer', 41, 3, 5, 41),
    ('Nova Iorque a LA', 'Entre as cidades mais culturalmente significativas dos EUA', 42, 3, 5, 42),
    ('Nós éramos adolescentes sonhando, se inclinando no banco da frente', '', 43, 3, 5, 43),
    ('Querido, vem me dar um beijo', '', 44, 3, 5, 44),
    ('Me coloca na capa da Rolling Stone', 'Rolling Stone é uma revista clássica de música e cultura pop', 45, 3, 5, 45),
    ('Jovens americanos modestos residenciais', 'Uptown se refere a alguém duma pequena cidade; down-home se refere a uma pessoa modesta e normalmente rural', 46, 3, 5, 46),
    ('Crescendo em casinhas rosas', '', 47, 3, 5, 47),
    ('Se beijando nos sofás da sala de estar', '''To make-out'' quer dizer se beijar, e talvez até um pouco mais sexual dependendo do contexto', 48, 3, 5, 48),
    ('Soprando aquela fumaça no sábado à noite', 'Provávelmente fumaça de maconha', 49, 3, 5, 49),
    ('Um pouco estragados, mas estamos todos bem', '', 50, 3, 5, 50);