insert into Lines
    (line_lyrics, line_explanation, line_index, song_instance_id, language_id)
values
    ('Nacimos para aguantar lo que el cuerpo sostiene', 'una buena explicación aqui xd', 1, 3, 2),
    ('Aguantamos lo que vino y aguantamos lo que viene', 'una buena explicación aqui xd', 2, 3, 2),
    ('Aguantamos aunque tengamos los segundos contados', 'una buena explicación aqui xd', 3, 3, 2),
    ('Nuestro cuerpo aguanta hasta quince minutos ahorcado', 'una buena explicación aqui xd', 4, 3, 2),
    ('Aguantamos latigazos, que nos corten los dos brazos', 'una buena explicación aqui xd', 5, 3, 2),
    ('Fractura en cualquier hueso, tres semanas con un yeso', 'una buena explicación aqui xd', 6, 3, 2),

    ('Aguantamos todo el tiempo las ganas de ir al baño', 'una buena explicación aqui xd', 7, 3, 2),
    ('Pa ver el cometa Halley, hay que aguantar setenta años', 'una buena explicación aqui xd', 8, 3, 2),
    ('Aguantamos la escuela, la facultad, el instituto', 'una buena explicación aqui xd', 9, 3, 2),
    ('A la hora de cenar nos aguantamos los eruptos', 'una buena explicación aqui xd', 10, 3, 2),
    ('El pueblo de Burundi sigue aguantando la hambruna', 'una buena explicación aqui xd', 11, 3, 2),
    ('Aguantamos tres días para llegar a la luna', 'una buena explicación aqui xd', 12, 3, 2),

    ('Aguantamos el frío del Ártico, el calor del trópico', 'una buena explicación aqui xd', 13, 3, 2),
    ('Aguantamos con anticuerpos los virus microscópicos', 'una buena explicación aqui xd', 14, 3, 2),
    ('Aguantamos las tormentas, huracanes, el mal clima', 'una buena explicación aqui xd', 15, 3, 2),
    ('Aguantamos Nagasaki, aguantamos Hiroshima', 'una buena explicación aqui xd', 16, 3, 2),
    ('Aunque no queramos, aguantamos nuevas leyes', 'una buena explicación aqui xd', 17, 3, 2),
    ('Aguantamos hoy por hoy que todavía existan reyes', 'una buena explicación aqui xd', 18, 3, 2),
    ('Castigamos al humilde y aguantamos al cruel', 'una buena explicación aqui xd', 19, 3, 2),
    ('Aguantamos ser esclavos por nuestro color de piel', 'una buena explicación aqui xd', 20, 3, 2),
    ('Aguantamos el capitalismo, el comunismo, el socialismo, el feudalismo', 'una buena explicación aqui xd', 21, 3, 2),
    ('Aguantamos hasta el pendejismo', 'una buena explicación aqui xd', 22, 3, 2),
    ('Aguantamos al culpable cuando se hace el inocente', 'una buena explicación aqui xd', 23, 3, 2),
    ('Aguantamos cada año a nuestro p*** presidente', 'una buena explicación aqui xd', 24, 3, 2),

    ('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 25, 3, 2),
    ('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 26, 3, 2),
    ('Por lo que venga y por este instante', 'una buena explicación aqui xd', 27, 3, 2),
    ('A brindar por el aguante', 'una buena explicación aqui xd', 28, 3, 2),
    ('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 29, 3, 2),
    ('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 30, 3, 2),
    ('Por lo que venga y por este instante', 'una buena explicación aqui xd', 31, 3, 2),
    ('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 32, 3, 2),
    ('A brindar por el aguante', 'una buena explicación aqui xd', 33, 3, 2),

    ('Aguantamos que Monsanto infecte nuestra comida', 'una buena explicación aqui xd', 34, 3, 2),
    ('Aguantamos el agente naranja y los pesticidas', 'una buena explicación aqui xd', 35, 3, 2),
    ('Cuando navegamos, aguantamos el mareo', 'una buena explicación aqui xd', 36, 3, 2),
    ('Aguantamos el salario mínimo y el desempleo', 'una buena explicación aqui xd', 37, 3, 2),
    ('Aguantamos las Malvinas y la invasion británica', 'una buena explicación aqui xd', 38, 3, 2),
    ('En la ciudad de Pompeya aguantamos lava volcánica', 'una buena explicación aqui xd', 39, 3, 2),

    ('Y dentro de la lógica de nuestra humanidad', 'una buena explicación aqui xd', 40, 3, 2),
    ('Nos creemos la mentira y nadie aguanta la verdad', 'una buena explicación aqui xd', 41, 3, 2),

    ('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 42, 3, 2),
    ('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 43, 3, 2),
    ('Por lo que venga y por este instante', 'una buena explicación aqui xd', 44, 3, 2),
    ('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 45, 3, 2),
    ('A brindar por el aguante', 'una buena explicación aqui xd', 46, 3, 2),

    ('Aguantamos al ateo, al mormón, al cristiano', 'una buena explicación aqui xd', 47, 3, 2),
    ('Al budista, al judío, aguantamos al pagano', 'una buena explicación aqui xd', 48, 3, 2),
    ('Aguantamos el que vende balas y el que las dispara', 'una buena explicación aqui xd', 49, 3, 2),
    ('Aguantamos la muerte de Lenon, la de Víctor Jara', 'una buena explicación aqui xd', 50, 3, 2),
    ('Aguantamos muchas guerras: Vietnam, la Guerra Fría', 'una buena explicación aqui xd', 51, 3, 2),
    ('La Guerra de los Cien Años, la Guerra de los Seis días', 'una buena explicación aqui xd', 52, 3, 2),
    ('Que aguanten la revancha venimos al desquite', 'una buena explicación aqui xd', 53, 3, 2),
    ('Hoy nuestro hígado aguanta lo que la barra invite', 'una buena explicación aqui xd', 54, 3, 2),

    ('Aguantamos ser esclavos por nuestro color de piel', 'una buena explicación aqui xd', 55, 3, 2),

    ('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 56, 3, 2),
    ('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 57, 3, 2),
    ('Por lo que venga y por este instante', 'una buena explicación aqui xd', 58, 3, 2),
    ('A brindar por el aguante', 'una buena explicación aqui xd', 59, 3, 2),

    ('Por lo que fue y por lo que pudo ser', 'una buena explicación aqui xd', 60, 3, 2),
    ('Por lo que hay, por lo que puede faltar', 'una buena explicación aqui xd', 61, 3, 2),
    ('Por lo que venga y por este instante', 'una buena explicación aqui xd', 62, 3, 2),
    ('Levante el vaso y a brindar por el aguante', 'una buena explicación aqui xd', 63, 3, 2),
    ('A brindar por el aguante', 'una buena explicación aqui xd', 64, 3, 2);

insert into Line_Translations
    (line_translation_lyrics, line_translation_explanation, line_id, language_id, song_instance_id, line_index)
values
    ('We were born to bare with what the body can handle', 'a good explanation here xd', 1, 1, 3, 1),
    ('We endured what came and we''ll endure what''s to come', 'a good explanation here xd', 2, 1, 3, 2),
    ('We put up even if we have the seconds counted', 'a good explanation here xd', 3, 1, 3, 3),
    ('Our body bears up to fifteen minutes hanging', 'a good explanation here xd', 4, 1, 3, 4),
    ('We put up with lashes, cutting both our arms', 'a good explanation here xd', 5, 1, 3, 5),
    ('Fractures in any bone, three weeks with a cast', 'a good explanation here xd', 6, 1, 3, 6),

    ('We always hold the urge to use the restroom', 'a good explanation here xd', 7, 1, 3, 7),
    ('To see Halley''s Comet, you have to wait seventy years', 'a good explanation here xd', 8, 1, 3, 8),
    ('We endure the school, the faculty, the institution', 'a good explanation here xd', 9, 1, 3, 9),
    ('At dinner time we hold our burps', 'a good explanation here xd', 10, 1, 3, 10),
    ('The village of Burundi is still enduring hunger', 'a good explanation here xd', 11, 1, 3, 11),
    ('We waited 3 days to reach the moon', 'a good explanation here xd', 12, 1, 3, 12),

    ('We endure the bitter cold of the Artic, the heat of the tropics', 'a good explanation here xd', 13, 1, 3, 13),
    ('With antibodies we endure microscopic viruses', 'a good explanation here xd', 14, 1, 3, 14),
    ('We endure storms, hurricanes, the bad climate', 'a good explanation here xd', 15, 1, 3, 15),
    ('We endured Nagasaki, we endured Hiroshima', 'a good explanation here xd', 16, 1, 3, 16),
    ('Though we may not want to, we put up with new laws', 'a good explanation here xd', 17, 1, 3, 17),
    ('We put up with the fact that kings still exist', 'a good explanation here xd', 18, 1, 3, 18),
    ('We punish the humble and we put up with the cruel', 'a good explanation here xd', 19, 1, 3, 19),
    ('We put up with slavery for the color of our skin', 'a good explanation here xd', 20, 1, 3, 20),
    ('We put up with capitalism, communism, socialism, feudalism', 'a good explanation here xd', 21, 1, 3, 21),
    ('We even endure stupidism', 'a good explanation here xd', 22, 1, 3, 22),
    ('We put up with the guilty when they pretend to be innocent', 'a good explanation here xd', 23, 1, 3, 23),
    ('We put up with our f***ing president every year', 'a good explanation here xd', 24, 1, 3, 24),

    ('For what was and for what it could have been', 'a good explanation here xd', 25, 1, 3, 25),
    ('For what there is, for what might be missing', 'a good explanation here xd', 26, 1, 3, 26),
    ('For whatever is coming, and for this instant', 'a good explanation here xd', 27, 1, 3, 27),
    ('Cheers! For endurance', 'a good explanation here xd', 28, 1, 3, 28),
    ('For what was and for what it could have been', 'a good explanation here xd', 29, 1, 3, 29),
    ('For what there is, for what might be missing', 'a good explanation here xd', 30, 1, 3, 30),
    ('For whatever is coming, and for this instant', 'a good explanation here xd', 31, 1, 3, 31),
    ('Raise your glass and let''s to toast our endurance', 'a good explanation here xd', 32, 1, 3, 32),
    ('Cheers! For endurance', 'a good explanation here xd', 33, 1, 3, 33),

    ('We put up with Monsanto infecting our food', 'a good explanation here xd', 34, 1, 3, 34),
    ('We put up with Agent Orange and pesticides', 'a good explanation here xd', 35, 1, 3, 35),
    ('When we sail, we put up with the dizziness', 'a good explanation here xd', 36, 1, 3, 36),
    ('We put up with the minimum wage and unemployment', 'a good explanation here xd', 37, 1, 3, 37),
    ('We put up with the Malvinas and British Invasion', 'a good explanation here xd', 38, 1, 3, 38),
    ('In Pompey, we put up volcanic lava', 'a good explanation here xd', 39, 1, 3, 39),

    ('And through our human logic', 'a good explanation here xd', 40, 1, 3, 40),
    ('We believe the lie and no one puts up with the truth', 'a good explanation here xd', 41, 1, 3, 41),

    ('For what was and for what it could have been', 'a good explanation here xd', 42, 1, 3, 42),
    ('For what there is, for what might be missing', 'a good explanation here xd', 43, 1, 3, 43),
    ('For whatever is coming, and for this instant', 'a good explanation here xd', 44, 1, 3, 44),
    ('Raise your glass and let''s to toast our endurance', 'a good explanation here xd', 45, 1, 3, 45),
    ('Cheers! For endurance', 'a good explanation here xd', 46, 1, 3, 46),

    ('We endure the Atheist, the Mormon, Christian', 'a good explanation here xd', 47, 1, 3, 47),
    ('The Buddhist, the Jew, we endure the Pagan', 'a good explanation here xd', 48, 1, 3, 48),
    ('We endure the one who sells the bullets, and the one who shoots them', 'a good explanation here xd', 49, 1, 3, 49),
    ('We endured the death of Lennon, Victor Jara', 'a good explanation here xd', 50, 1, 3, 50),
    ('We endured many wars: Vietnam, The Cold War', 'a good explanation here xd', 51, 1, 3, 51),
    ('The One Hundred Years War, the Six Days War', 'a good explanation here xd', 52, 1, 3, 52),
    ('Make them wait for the rematch, we came for revenge', 'a good explanation here xd', 53, 1, 3, 53),
    ('Today our liver endures what the bar invites', 'a good explanation here xd', 54, 1, 3, 54),

    ('We put up with slavery for the color of our skin', 'a good explanation here xd', 55, 1, 3, 55),

    ('For what was and for what it could have been', 'a good explanation here xd', 56, 1, 3, 56),
    ('For what there is, for what might be missing', 'a good explanation here xd', 57, 1, 3, 57),
    ('For whatever is coming, and for this instant', 'a good explanation here xd', 58, 1, 3, 58),
    ('Cheers! For endurance', 'a good explanation here xd', 59, 1, 3, 59),

    ('For what was and for what it could have been', 'a good explanation here xd', 60, 1, 3, 60),
    ('For what there is, for what might be missing', 'a good explanation here xd', 61, 1, 3, 61),
    ('For whatever is coming, and for this instant', 'a good explanation here xd', 62, 1, 3, 62),
    ('Raise your glass and let''s to toast our endurance', 'a good explanation here xd', 63, 1, 3, 63),
    ('Cheers! For endurance', 'a good explanation here xd', 64, 1, 3, 64);